# run on container environment
sudo: false

language: php

cache:
    apt: true
    directories:
      - node_modules
      - vendor

notifications:
    email:
        on_success: change
        on_failure: always

php:
    - 7.2
    - 7.1
    - 7.0

env:
    # latest:
    - WP_VERSION=latest
    # nightly:
    - WP_VERSION=nightly

matrix:
    fast_finish: true
    allow_failures:
        # allow failures on nightlies:
        - env: WP_VERSION=nightly

install:
    - composer install --no-interaction

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
    - |
      export WP_MULTISITE=0
      ./vendor/bin/phpunit -v --exclude-group=ms-required
    - |
      export WP_MULTISITE=1
      ./vendor/bin/phpunit -v --exclude-group=ms-excluded
    - |
      ./vendor/bin/phpcs -n -p -s --colors .
